import { HeaderNavigation } from "@/components/Header";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
// export const interVariable = localFont({ // essa aqui
//   src: "./fonts/Inter-Variable.ttf",
//   variable: "--font-inter-variable",
//   weight: "100 900"
// })
export const lexendVariable = localFont({ // essa aqui
  src: "./fonts/Lexend-Variable.ttf",
  variable: "--font-lexend-variable",
  weight: "100 900"
})

export const metadata: Metadata = {
  title: "Repositório Mental",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={` ${lexendVariable.variable} antialiased`}
      >
        <HeaderNavigation />
        {children}
      </body>
    </html>
  );
}
